title: Khaled Elsayed
description: IT IS and Cybersecurity Professional
url: https://khalled01.github.io
baseurl: ""
github_username: khalled01
minimal_mistakes_skin: default
search: true

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true

author:
  name: Khaled Elsayed
  avatar: /assets/images/bio-photo.jpg
  bio: IT IS and Cybersecurity Professional
  links:
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/khaledelsayed01/
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/khalled01

footer:
  links:
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/khaledelsayed01/
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/khalled01