# Site settings
title: "Khaled Elsayed"
email: ""
description: "IT, IS & Cybersecurity Professional"
baseurl: ""
url: "https://khalled01.github.io"
twitter_username: ""
github_username: "khalled01"
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Africa/Cairo

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

author:
  name: "Khaled Elsayed"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "IT, IS & Cybersecurity Professional"
  location: "Cairo, Egypt"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/khaledelsayed01/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/khalled01"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/khaledelsayed01/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/khalled01"